# Generated by Django 4.2.8 on 2024-01-21 01:46

import constrainedfilefield.fields.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('new', 'New')], default='new', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_requests', to='clients.client', verbose_name='Author')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients_requests', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Clients request',
                'verbose_name_plural': 'Clients requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientsRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(verbose_name='Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('format', models.CharField(max_length=15, verbose_name='File format')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('media', 'Медиа'), ('attachment', 'Приложение')], default='attachment', max_length=15, verbose_name='Attachment type')),
                ('attach_file', constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=('application/pdf', 'image/png', 'image/jpg', 'image/jpeg'), max_upload_size=1024000, mime_lookup_length=4096, null=True, upload_to='attachments', verbose_name='Attachment file')),
                ('clients_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clients_requests.clientsrequest', verbose_name='Clients`s request')),
            ],
            options={
                'verbose_name': 'Attachment of the request',
                'verbose_name_plural': 'Attachments of the request',
            },
        ),
    ]
