# Generated by Django 4.1.7 on 2023-02-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('new', 'New')], default='new', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Clients request',
                'verbose_name_plural': 'Clients requests',
            },
        ),
        migrations.CreateModel(
            name='ClientsRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(verbose_name='Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('format', models.CharField(max_length=15, verbose_name='File format')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('media', 'Медиа'), ('attachment', 'Приложение')], default='attachment', max_length=15, verbose_name='Attachment type')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='attachments/', verbose_name='Attachment file')),
            ],
            options={
                'verbose_name': 'Attachment of the request',
                'verbose_name_plural': 'Attachments of the request',
            },
        ),
        migrations.CreateModel(
            name='ClientsRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('new', 'New')], default='new', max_length=20, verbose_name='Status')),
                ('clients_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='clients_requests.clientsrequest', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Clients`s request history',
                'verbose_name_plural': 'Clients`s requests history',
            },
        ),
    ]
