# Generated by Django 4.2.8 on 2024-01-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clients request', 'verbose_name_plural': 'Clients requests'},
        ),
        migrations.RemoveField(
            model_name='clientsrequest',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='clientsrequest',
            name='update_dt',
        ),
        migrations.AddField(
            model_name='clientsrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2024, 1, 1, 7, 39, 21, 204237, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
