# Generated by Django 4.2.8 on 2024-01-05 08:11

import constrainedfilefield.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_requests', '0004_delete_clientsrequesthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsrequestattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='clientsrequestattachment',
            name='attach_file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=('application/pdf', 'image/png', 'image/jpg', 'image/jpeg'), max_upload_size=1024000, mime_lookup_length=4096, null=True, upload_to='attachments', verbose_name='Attachment file'),
        ),
    ]
