FROM python:3.12

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /clients_portal

# install dependences
COPY ./requirements.txt /clients_portal/requirements.txt
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r /clients_portal/requirements.txt

RUN apt-get -y update
RUN apt-get install gettext -y

# set display port to avoid crash
ENV DISPLAY=:99

# set open port
EXPOSE 8025











