# Generated by Django 4.2.4 on 2023-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salary (max)'),
        ),
    ]
