# Generated by Django 4.2.4 on 2023-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
