# Generated by Django 4.2.4 on 2023-12-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_company_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproject',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
