# Generated by Django 4.2.4 on 2023-12-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_testproject_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproject',
            name='finish_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In process'), ('completed', 'Completed'), ('on_checking', 'On checking'), ('rejected', 'Rejected')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
