# Generated by Django 4.2.4 on 2023-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_testproject_finish_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='full_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
