# Generated by Django 4.2.8 on 2023-12-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_position_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='intensity',
            field=models.IntegerField(default=1, verbose_name='Hiring intensity'),
        ),
    ]
