# Generated by Django 4.2.8 on 2023-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_vacancy_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('resume_sent', 'Resume sent'), ('rejected', 'Rejected'), ('invited_to_an_interview', 'Invited to an interview'), ('received_task', 'Received task'), ('completed_task', 'Completed task'), ('task_sent', 'Task sent'), ('passed', 'Passed'), ('old', 'Old')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
