# Generated by Django 4.2.8 on 2024-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН Агента')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование Агента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон Агента')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('activ', 'Активен'), ('not_activ', 'Не активен'), ('new', 'Новый')], default='new', max_length=20, verbose_name='Status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('products', models.ManyToManyField(blank=True, related_name='clients', to='products.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
            },
        ),
    ]
