# Generated by Django 4.1.7 on 2023-02-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН Агента')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование Агента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон Агента')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('activ', 'Активен'), ('not_activ', 'Не активен'), ('new', 'Новый')], default='new', max_length=20, verbose_name='Status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('values', models.TextField(blank=True, null=True, verbose_name='Values')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Clients history',
                'verbose_name_plural': 'Clients history',
            },
        ),
    ]
