# Generated by Django 4.2.8 on 2024-01-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2024, 1, 1, 7, 39, 8, 844858, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
    ]
