# Generated by Django 4.2.8 on 2024-01-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsHistory',
        ),
    ]
