# Generated by Django 4.2.8 on 2024-01-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=250, verbose_name='Price`s name')),
                ('file', models.FileField(upload_to='price_list/%y/%m/%d/', verbose_name='File')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Number of downloads')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Прайс лист',
                'verbose_name_plural': 'Прайс листы',
                'ordering': ['-created_at'],
            },
        ),
    ]
