# Generated by Django 4.1.7 on 2023-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
