# Generated by Django 4.2.8 on 2024-01-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pricelist_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прайс лист', 'verbose_name_plural': 'Прайс листы'},
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='updated',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2024, 1, 1, 7, 39, 27, 760127, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of downloads'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(upload_to='price_list/%y/%m/%d/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Price`s name'),
        ),
    ]
